name: superkauf
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+14

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  supabase_flutter: ^2.3.3
  equatable: ^2.0.5
  bloc: ^8.1.3
  flutter_bloc: ^8.1.4
  google_fonts: ^6.1.0
  get_it: ^7.6.4
  easy_localization: ^3.0.3
  dio: ^5.4.0
  pretty_dio_logger: ^1.3.1
  freezed: ^2.4.6
  freezed_annotation: ^2.2.0
  retrofit: ^4.0.3
  json_annotation: ^4.8.1
  font_awesome_flutter: ^10.7.0
  flutter_dotenv: ^5.1.0
  flutter_svg: ^2.0.9
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1
  easy_image_viewer: ^1.4.1
  google_sign_in: ^6.2.1
  card_loading: ^0.3.2
  flutter_cache_manager: ^3.3.1
  flutter_image_compress: ^2.1.0
  path_provider: ^2.1.2
  isar_flutter_libs: ^3.1.0+1
  hive: ^2.2.3
  posthog_flutter: ^4.0.0
  onesignal_flutter: ^5.1.0
  sliding_up_panel: ^2.0.0+1
  lottie: ^3.0.0
  flutter_carousel_widget: ^2.2.0
  path_drawing: ^1.0.1
  url_launcher: ^6.2.4
  open_mail_app: ^0.4.5
  gap: ^3.0.1
  hive_flutter: ^1.1.0
  googleapis: ^13.0.0
  googleapis_auth: ^1.4.2
  meilisearch: ^0.16.0
  sentry_flutter: ^7.17.0
  textfield_tags: ^3.0.1
  easy_debounce: ^2.0.3
  shared_preferences: ^2.2.2
#  flutter_native_splash: ^2.3.10


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.3.3
  json_serializable: ^6.6.0
  retrofit_generator: ^8.0.4
  freezed_annotation: ^2.4.1
  flutter_launcher_icons: ^0.13.1


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo4.png"
  image_path_android: "assets/images/logo4.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#715DF2"
  adaptive_icon_foreground: "assets/images/logo4.png"
flutter_native_splash:
  color: "#FFF2F2"
  image: "assets/images/logo1.png"
  android: true
  ios: true

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/images/
    - assets/blobs/
    - assets/lottie/
    - assets/superkauf-account.json
    - .env
